apiVersion: v1
kind: Service
metadata:
  name: postgres-node-1
spec:
  selector:
    app: postgres-node-1
  publishNotReadyAddresses: true
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
