apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgres-node-1
  labels:
    app: postgres
spec:
  accessModes: [ ReadWriteOnce ]
  storageClassName: hostpath # overridden in deployed env
  resources:
    requests:
      storage: 10Gi
